### ISSUE TITLE
Fixing duration detection for FLAC files?

### ISSUE THREAD

**Issue by xfzv** [Sonico98/exifaudio.yazi#4]
This isn't an issue with the plug-in itself but rather with `exiftool`, which reports wrong duration for FLAC files:

```console
% exiftool -ver
12.76
```

```console
% exiftool -Duration file-1.flac
Duration                        : 0:04:39

% mediainfo --Output=$'General;Duration: %Duration/String3%\r' file-1.flac
Duration: 00:06:51.870
```

```console
% exiftool -Duration file-2.flac
Duration                        : 0:02:48

% mediainfo --Output=$'General;Duration: %Duration/String3%\r' file-2.flac
Duration: 00:04:08.150
```

Just wondering if this could be improved.

It seems that `mediainfo` does a better job overall, as `exiftool` cannot read `ape`,`wav` or `wv` tags for example.

**Comment by Sonico98** [comment]
I could look into using mediainfo by default and exiftool as a fallback. Thanks for pointing this out!

**Comment by Sonico98** [comment]
This has been implemented in the mediainfo branch, unix-only for now until I figure out a way to access the template.txt file on Windows. Please test it if you can.
Mediainfo is preferred for displaying the file's metadata, but exiftool is still required for extracting (and thus displaying) the cover art. If mediainfo can't be found, exiftool is used for everything instead.

**Comment by xfzv** [comment]
Thanks!

Works fine on my end. A minor issue is values spacing compared to `exiftool`, they overlap cover art:

![Untitled](https://github.com/user-attachments/assets/2273200f-8c0c-420a-af0d-66fd604e4930)

**Comment by Sonico98** [comment]
> Thanks!
> 
> Works fine on my end. A minor issue is values spacing compared to `exiftool`, they overlap cover art:
> 
> ![Untitled](https://private-user-images.githubusercontent.com/78810647/350906296-2273200f-8c0c-420a-af0d-66fd604e4930.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTE1NzcsIm5iZiI6MTcyMTY1MTI3NywicGF0aCI6Ii83ODgxMDY0Ny8zNTA5MDYyOTYtMjI3MzIwMGYtOGMwYy00MjBhLWFmMGQtNjZmZDYwNGU0OTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEyMjc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMTBmNzgyMGIxZDk4NTdiNzVkODllNDExNGFkZjMzODA2YzNhYTZjZmIzYTFmYWY4NWFhMDFkN2I5NTViYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pIdFXdCnKQhTfc7I1mFH5XUpX0bO1vPKpeJ20WhIBwI)

Is the `template.txt` file present inside `~/.config/yazi/plugins/exifaudio.yazi`? Because if it is, the plugin is not picking it up.

**Comment by xfzv** [comment]
Sorry, I didn't notice `template.txt` file. All good now:

![Untitled](https://github.com/user-attachments/assets/ab0b2daf-b134-4f31-87a1-ffc546afc7f5)

**Comment by Sonico98** [comment]
Reimplemented without the need for a template file in the plugin directory, should work under Windows now as well (haven't tested). Closing for now.
